### ISSUE TITLE
Major Bug in search.js

### ISSUE THREAD

**Issue by Pancham97** [wzpan/hexo-theme-freemind#86]
When typing the search keyword "this is a " on the [demo website](https://www.hahack.com/hexo-theme-freemind-blog/), it shows the `.search-keyword` class in the search result. This is a major bug. Could you please address this issue?

<img width="338" alt="Screenshot 2020-04-03 at 1 25 07 PM" src="https://user-images.githubusercontent.com/10232900/78337472-a028a900-75ae-11ea-92f7-70242076e279.png">

**Comment by wzpan** [comment]
Aha. That's weird. I will figure out what's the problem.

**Comment by Pancham97** [comment]
Thanks! Did you get a solution yet?

I am unable to figure out why this is happening in the first place. Isn't the search taking place in the JSON file generated by `content.json`?

Please let me know when you find a solution. This has ruined my sleep.

**Comment by wzpan** [comment]
I found out the reason.

The search process is fuzzy and the search.js will try to highlight each word of the search text. 
Hence all `is` will be replaced by `<em class="search-keyword">is</em>` and then all `a` including all the `a` letter in `<em class="search-keyword">is</em>` will be replaced by `<em class="search-keyword">a</em>`. Then we get `<em cl<em class="search-keyword">a</em>ss="se<em class="search-keyword">a</em>rch-keyword">is</em>`.

If you don't need the fuzzy search. I think simply modify [this line](https://github.com/wzpan/hexo-theme-freemind/blob/master/source/js/search.js#L42) as:

``` js
var keywords = this.value.trim().toLowerCase();
```

will resolve the problem. 

Alternatively if your article is mainly written in English that each word will be separated by a space, you can modify these [two lines](https://github.com/wzpan/hexo-theme-freemind/blob/master/source/js/search.js#L106) as:

``` js
var regS = new RegExp(' '+keyword, "gi");
match_content = match_content.replace(regS, " <em class=\"search-keyword\">" + keyword + "</em>");
```

But I won't modify the search.js in hexo-theme-freemind. Because some language like Chinese doesn't use spaces to connect words.

**Comment by Pancham97** [comment]
Thank you for providing solutions to it. However, I have a couple of doubts that need to be cleared.

1. Your first solution will not work for multiple word search, will it? For example, if I search for 'this is a', will it search for all the 3 words as it used to?

2. Your second solution does not take care of special characters, and also does not work for multiple word search. When searching for multiple words, it returns some weird string with all the words convoluted / merged together.

Can you please look into it again?

My articles are written only in English and code blocks.

Much appreciated!

**Comment by wzpan** [comment]
1. It will use `this is a` as the search keyword. However it won't be fuzzy matching. For instance,

    > This is a good idea.    // will match

    > This is good. What a wonderful idea.  // will not match

2. It should work for multiple word search. Can you give me some bad cases?

**Comment by Pancham97** [comment]
It doesn't seem to work for me, Pan.

I need the fuzzy search.

**Comment by wzpan** [comment]
@Pancham97 Have you tried the second scenario?

**Comment by Pancham97** [comment]
Hey Pan,

Thanks for your suggestions, brother. I just found out that I was making a mistake by storing it in array (using the `split()` method), and then using the index to find the `firstOccur`. Silly mistake. Thanks for your advice!

It now seems to work for multiple keywords, albeit non-fuzzy. But, works for me.

Thanks again!
Have a great day!

**Comment by citizensanction** [comment]
this worked very well for me... to replace those two lines in the search.js for english content. however, is there a way to reverse the order of the search results?  for me, the results seem to be displayed in reverse alphabetical order (i.e. from Z-A) 
Thanks
